apiVersion: v2
name: didwebvh-server-py
description: didwebvh-server-py - dev
type: application
version: 0.5.0
appVersion: "0.5.0"
dependencies:
  - name: didwebvh-server-py
    version: 0.5.0
    repository: https://github.com/decentralized-identity/didwebvh-server-py/tree/gh-pages
