apiVersion: v2
name: didwebvh-server-py
description: didwebvh-server-py - dev
type: application
version: 0.4.5
appVersion: "0.4.5"
dependencies:
  - name: didwebvh-server-py
    version: 0.4.5
    repository: https://identity.foundation/didwebvh-server-py
