apiVersion: v2
name: vc-authn-oidc
description: vc-authn-oidc - dev
type: application
version: 1.0.0
appVersion: "2.3.6"
dependencies:
  - name: vc-authn-oidc
    version: 1.0.0
    repository: https://openwallet-foundation.github.io/helm-charts/
