apiVersion: v2
name: vc-authn-oidc
description: vc-authn-oidc - dev
type: application
version: 0.4.5
appVersion: "2.3.4"
dependencies:
  - name: vc-authn-oidc
    version: 0.4.5
    repository: https://openwallet-foundation.github.io/acapy-vc-authn-oidc
