apiVersion: v2
name: vc-authn-oidc
description: vc-authn-oidc - dev
type: application
version: 0.4.4
appVersion: "2.3.2"
dependencies:
  - name: vc-authn-oidc
    version: 0.4.4
    repository: https://openwallet-foundation.github.io/acapy-vc-authn-oidc
