apiVersion: v2
name: endorser-service
description: endorser-service - sandbox
type: application
version: 0.1.0
appVersion: "1.1.1"
dependencies:
  - name: endorser-service
    version: 0.1.0
    repository: https://openwallet-foundation.github.io/helm-charts
