global:
  ingressSuffix: -sandbox.apps.silver.devops.gov.bc.ca

endorser-service:
  api:
    image:
      tag: 1.1.2
    acapyAdminUrl: https://endorser-agent-webvh-admin-sandbox.apps.silver.devops.gov.bc.ca
    publicName: "BC Endorser Service (sandbox)"
    publicDesc: "An endorser service for BC issuer agents"
    adminUser: endorser-admin
    logLevel: info
    autoAcceptConnections: true
    autoAcceptAuthors: true
    autoEndorseRequests: true
    autoEndorseTxnTypes: ""

  acapy:
    image:
      tag: 1.1.2
    agentUrl: "https://endorser-agent-webvh-sandbox.apps.silver.devops.gov.bc.ca"
    adminUrl: "https://endorser-agent-webvh-admin-sandbox.apps.silver.devops.gov.bc.ca"
    plugin-config.yml:
      webvh:
        server_url: "https://sandbox.bcvh.vonx.io"

  proxy:
    ingress:
      hosts:
        - host: endorser-agent-webvh-sandbox.apps.silver.devops.gov.bc.ca
          paths:
            - path: /
              pathType: ImplementationSpecific
              servicePort: agent
        - host: endorser-agent-webvh-admin-sandbox.apps.silver.devops.gov.bc.ca
          paths:
            - path: /
              pathType: ImplementationSpecific
              servicePort: admin
        - host: endorser-api-webvh-sandbox.apps.silver.devops.gov.bc.ca
          paths:
            - path: /
              pathType: ImplementationSpecific
              servicePort: endorser
