global:
  ingressSuffix: .apps.silver.devops.gov.bc.ca

endorser-service:
  api:
    acapyAdminUrl: https://endorser-agent-webvh-admin.apps.silver.devops.gov.bc.ca
    publicName: "BC Endorser Service"
    publicDesc: "An endorser service for BC issuer agents"
    adminUser: endorser-admin
    logLevel: info
    autoAcceptConnections: true
    autoAcceptAuthors: true
    autoEndorseRequests: true
    autoEndorseTxnTypes: ""

  acapy:
    agentUrl: "https://endorser-agent-webvh.apps.silver.devops.gov.bc.ca"
    adminUrl: "https://endorser-agent-webvh-admin.apps.silver.devops.gov.bc.ca"
    plugin-config.yml:
      webvh:
        server_url: "https://registry.digitaltrust.gov.bc.ca"

  proxy:
    ingress:
      hosts:
        - host: endorser-agent-webvh.apps.silver.devops.gov.bc.ca
          paths:
            - path: /
              pathType: ImplementationSpecific
              servicePort: agent
        - host: endorser-agent-webvh-admin.apps.silver.devops.gov.bc.ca
          paths:
            - path: /
              pathType: ImplementationSpecific
              servicePort: admin
        - host: endorser-api-webvh.apps.silver.devops.gov.bc.ca
          paths:
            - path: /
              pathType: ImplementationSpecific
              servicePort: endorser
            - path: /
              pathType: ImplementationSpecific
              servicePort: endorser
