apiVersion: v2
name: didcomm-mediator-credo
description: didcomm-mediator-credo - dev
type: application
version: 0.6.1
appVersion: "0.1.0"
dependencies:
  - name: didcomm-mediator-credo
    version: 0.6.1
    repository: https://openwallet-foundation.github.io/helm-charts
