apiVersion: v2
name: didcomm-mediator-credo
description: didcomm-mediator-credo - prod
type: application
version: 0.4.0
appVersion: "0.1.0"
dependencies:
  - name: didcomm-mediator-credo
    version: 0.4.0
    repository: https://openwallet-foundation.github.io/helm-charts
